### ISSUE TITLE
a real TR not found by TRiCoLOR

### ISSUE THREAD

**Issue by Jesson-mark** [davidebolo1993/TRiCoLOR#11]
Hi, I'm using TRiCoLOR to find tandem repeats from two HiFi data of two human samples named C1 and C2. 
By comparing the two vcf files generated TRiCoLOR REFER, I found a TR in C1 but not in C2. This TR locus is chr2:24491500-24491501. 
```bash
$ tabix C1.vcf.gz chr2:24491500-24491501
chr2    24491500        .       GC      GCGGCGGCGGCGGCGGCAGGCGCCTGGGCCCAGGGGGCCG        .       .       TREND=24491501;TRLEN=40;RAED=38;AED=0;MAPQ1=60;MAPQ2=60;H1M=GCG;H1N=6;H2M=GCG;H2N=6     GT:DP1:DP2     1|1:34:17

```
As you can see this is a GCG repeat. But this TR is not found in vcf file of C2. Here are TRs within chr2:24470000-24510000 in C2: 
![image](https://user-images.githubusercontent.com/49034603/135377030-12a04b65-9f25-496b-82c4-90a9eb9e3402.png)

When I check the raw bam of C2, which is used for TRiCoLOR to find TR, I found the TR is just in C2! Here is igv plot of two raw bam files and four haplotype.bam files generated by REFER: 
![image](https://user-images.githubusercontent.com/49034603/135379388-cd1f3592-e687-4bf6-b9bb-02bbbde3a947.png)
C2_h1 is bam file of haplotype1 of C2 and C2_h2 is bam file of haplotype2 of C2. So is C1. 

Well you can see there is a 38bp insertion in two raw bam files and this insertion is just the TR found in C1. 
I don't understand why this TR is not found in C2. Are there any parameters influencing this?

**Comment by davidebolo1993** [comment]
Hi @Jesson-mark,

thanks for reporting. It would be nice if you can share the haplo-tagged C1 and C2 bam files so that I can investigate further. 
In principle this can be either an issue with the phasing step (if those reads are not properly tagged, then they are ignored by REFER) or with the re-alignment step of the consensus, which ends up being mapped elsewhere on chromosome 2. It seems to me that the TR calling parameters are working just fine because of the TR in C1 being properly resolved by the consensus algorithm and called.

Thanks,

Davide

**Comment by Jesson-mark** [comment]
Thanks for you reply. I think maybe it's better for us to communicate using email. 
Is your google email still in use? 
If so, I will send you an email attached part of the haplo-tagged C1 and C2 bam files.

**Comment by davidebolo1993** [comment]
Sure, go ahead.

Best,

Davide

**Comment by davidebolo1993** [comment]
Solved by e-mail by providing to REFER a shared BED derived from merging SENSoR BED files for C1 and C2 samples.

Thanks, @Jesson-mark
