### ISSUE TITLE
Is Tricolor appropriate for calling tandem repeats for PacBio HiFi data?

### ISSUE THREAD

**Issue by LiShuhang-gif** [davidebolo1993/TRiCoLOR#12]
Hi, 
I have some sequencing data from PacBio HiFi and now I'm planning to use Tricolor to call TR de novo. However, in the paper about TRiCoLor, I've found that SENSoR has been trained to identify regions with low entropy in error-prone long-reads. So I just want to make sure whether Tricolor is appropriate for calling tandem repeats for PacBio HiFi data (which is 40× and should have low error rate). Thanks!

**Comment by davidebolo1993** [comment]
Hi  @LiShuhang-gif, 

thanks for getting in touch. The REFER module should benefit from low-error reads (because of the RegEx algorithm being more accurate with decreasing error rates). I have to say that SENSoR has not been trained on HiFi reads and I guess that the default entropy threshold is not appropriate for those reads. However, one can experiment with different entropy threshold values for a couple of regions containing known STRs for an organism of interest and set the new threshold to that value. I hope this is clear enough. Feel free to get in touch if you need help.

Best,

Davide

**Comment by LiShuhang-gif** [comment]
Thank you for your prompt reply! One more question is, should I turn the entropy threshold up or down for PacBio HiFi data? Do you have any suggestions for this?

**Comment by Jesson-mark** [comment]
Hi, I've encountered the same problem as @LiShuhang-gif and need to adjust the parameters of SENSoR for HiFi reads. 
The help page of SENSoR says `-l` means "minimum length of the entropy drops [30]" and "entropy drop" is also used in method section of your paper. I'm a little confused about the entropy drops. Can you explain it more specificly? 

Thanks.

**Comment by davidebolo1993** [comment]
Hi @Jesson-mark and @LiShuhang-gif, 

> The help page of SENSoR says -l means "minimum length of the entropy drops [30]" and "entropy drop" is also used in method section of your paper. I'm a little confused about the entropy drops. Can you explain it more specificly?

Shannon entropy is a measure of how repetitive are certain strings (i.e. certain DNA segments). In TRiCoLOR, this is calculated, for each read, using non-overlapping sliding windows (30 bp-size). Entropy is low when those DNA segments overuse certain characters (that is, certain nucleotides), and gets higher as long as the randomness increases. 
For instance:

```python
import math

def entropy(substr):

	'''
	Calculate Shannon entropy of a (sub)string
	'''

	prob = [float(substr.count(x)) / len(substr) for x in dict.fromkeys(list(substr))]
	entropy = - sum([p * math.log(p) / math.log(2.0) for p in prob])

	return entropy


s1="AATCTAACAATCAATACGGCACGCGTAGCG" #random 30bp string
s2="GGCGGCGGCGGCGGCGGCACGGCGCGGCGG" #repetitive 30bp string

entropy(s1)
#1.9344518194827178
entropy(s2)
#1.1092271387984602
```
Based on our experiments, we see that repetitive 30 bp-windows (that is, 30 bp-windows covering an annotated short TR) have usually entropy < 1.23 (entropy drop) while this value is usually higher (>1.7) for 30 bp-windows not covering annotated TRs.

> should I turn the entropy threshold up or down for PacBio HiFi data? Do you have any suggestions for this?

I'm afraid there is no easy answer to this question (it depends on the length of the repetitive motif). I think one can start by setting a high entropy threshold (something like 1.8) so that most of the regions (even those that are not repetitive) are included in the final BED from SENSoR. Then, you can intersect the output from SENSoR with a BED containing known TRs (for the human GRCh38 reference, these are available in the TRiCoLOR [repo](https://github.com/davidebolo1993/TRiCoLOR/tree/master/paper/data) and maybe average those values. [Bedtools](https://bedtools.readthedocs.io/en/latest/) should have functions to facilitate your analysis. 

Hope this answers your questions.

Best, 

Davide

**Comment by Jesson-mark** [comment]
I got it. Thanks for your considerate reply. 

Best wishes, 

Jesson-mark

**Comment by lauragails** [comment]
Hi all! I've made it to Step1 and Step2 on long read data and it's taking an insane amount of memory. 

Could it be because this parameter is tuned incorrectly? Right now it's failing at 400GB memory. 

Thank you!
