### ISSUE TITLE
Running TRiCoLOR on multiple samples simultaneously

### ISSUE THREAD

**Issue by wdecoster** [davidebolo1993/TRiCoLOR#3]
Hi,

While running your tool I noticed that TRiCoLOR creates separate fasta files per chromosome and mmi indices. I wonder if that makes it unsafe to run multiple samples in parallel, as they'll attempt to create the same file(s). If I understood correctly the tool checks if the .fa per chromosome exists (https://github.com/davidebolo1993/TRiCoLOR/blob/master/TRiCoLOR/REFER/REFER.py#L232) but not if the .mmi already exists (and I didn't check what minimap2 does when asked to create an index that already exists...).

Besides that, I would very much like it if TRiCoLOR (perhaps optionally) used a temp folder for these chromosome fasta files and indices and didn't start writing to my directory with genome files. I see the tool checks if the directory is writable (which is probably often not the case if that folder is shared across users). The core python `tempfile` module is quite good for that, also making sure things are cleaned up at the end. Although one could argue that it's not a bad thing to keep these indices for reuse, and a `TRiCoLOR index` subcommand might be useful to avoid creating these over and over again and store them in a user-chosen directory, before running any samples... just a thought :) 

Cheers,
Wouter

**Comment by davidebolo1993** [comment]
Hi @wouter,

suggestions are always very much appreciated, thanks for that. 
- I'll add a check for the .mmi indexes. Minimap2 overwrites the pre-existent chromosome index when called with -d and this indeed can cause problems when running TRiCoLOR in parallel on multiple samples.
- Overall, my impression is that storing the chromosome .mmi indexes ready is useful for routine analyses. I can briefly rework the code so that these indexes are stored into an user-defined folder rather than into the genome-containing folder.

I'll let you know when it's done.

Best,
Davide

**Comment by davidebolo1993** [comment]
BTW, just noticed that a check for the .mmi was already there (if I got your first point right).

https://github.com/davidebolo1993/TRiCoLOR/blob/6969335b7b6d3315703d1aa21ef7b525b61a7a9e/TRiCoLOR/REFER/REFER.py#L215-L251

**Comment by davidebolo1993** [comment]
I'm also done with the second point. For the time being, I feel that storing the indexes in a non-temporary folder is the way to go. Both REFER and SAGE now accept a --mmidir parameter in which indexes are stored (and from which these are read). Just tested with the example in the documentation and everything worked just fine. Feel free to re-open if I missed something.
